---
name: 🚀 Feature Request
about: Suggest a feature or enhancement
title: "[Feature] "
labels: enhancement
assignees: ''

---

## Summary
A clear and concise description of the feature you’re requesting.

## Why Is This Feature Needed?
Explain why this feature would be useful to the project.

## Detailed Description
Describe how you want the feature to work. Include any alternative approaches you’ve considered.

## Affected Component
Which part of the monorepo does this request affect?
- [ ] Grammar Checker Demo Website
- [ ] Chrome Extension

## Additional Notes
Anything else you want to mention.
